[package]
name = "rust-searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22"
egui = "0.22"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
rayon = "1.7"
